### ISSUE TITLE
List not loading after tweaking confidence in courses

### ISSUE THREAD

**Issue by Saisanjeevr** [HarshitSohaney/Bugbyte#3]
Hi!

I did this:

    1) Go to a course
    2) Change the course confidence 
    3) Go to the main task list
![buginaction](https://github.com/HarshitSohaney/Bugbyte/assets/126698585/119bd611-2fe4-4eef-a774-37bac87237f4)

The list did not load at that point. However, if I go back to a course, and then reload the main list, the list loads again.
![image](https://github.com/HarshitSohaney/Bugbyte/assets/126698585/d9975e49-6e97-46b9-9886-a1d52072e73d)

I have checked if I removed assignments by mistake, and I'm sure that all my courses and assignments are in place.

Thanks for checking!

**Comment by HarshitSohaney** [comment]
I think this is an issue with too many updates to the User profile database, theres a deadlock somewhere. Another puzzling thing is that all the course priorities show as 2. hmmmm weird
I'll look into fixing it! Thanks for pointing it out

**Comment by HarshitSohaney** [comment]
Fixed, it was a deadlock issue. Fixed using atomic transactions!
